services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: bnck-codeflix-typescript:latest
    container_name: bnck-codeflix-typescript
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules